# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название категории')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название фильма')),
                ('image', models.CharField(max_length=64, verbose_name='Обложка')),
                ('preview', models.CharField(blank=True, max_length=64, verbose_name='Превью')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ManyToManyField(to='mainApp.Categories', verbose_name='Категории')),
            ],
        ),
    ]
