# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
            preserve_default=False,
        ),
    ]
